spring.application.name=TodoListSpringBoot

spring.datasource.url=jdbc:postgresql://localhost:5432/todolist_springboot
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver